/** Declaration file generated by dts-gen */

export = proofreader;

declare class proofreader {
    constructor();

    addDictionary(dicFilePath: any, affFilePath: any): void;

    proofread(html: any): any;

    setBlacklist(value: any): void;

    setWhitelist(value: any): void;

    setWriteGoodSettings(settings: any): void;

    static version: string;

}

declare namespace proofreader {
    namespace prototype {
        function addDictionary(dicFilePath: any, affFilePath: any): void;

        function proofread(html: any): any;

        function setBlacklist(value: any): void;

        function setWhitelist(value: any): void;

        function setWriteGoodSettings(settings: any): void;

        namespace addDictionary {
            const prototype: {
            };

        }

        namespace proofread {
            const prototype: {
            };

        }

        namespace setBlacklist {
            const prototype: {
            };

        }

        namespace setWhitelist {
            const prototype: {
            };

        }

        namespace setWriteGoodSettings {
            const prototype: {
            };

        }

    }

}

